[package]
name = "pdforum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
axum = "0.7.7"
pdf-writer = "0.12.0"
tokio = { version = "1.40.0", features = ["full"] }

